name: scrape
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          # Install a specific version of uv.
          version: "0.4.28"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Scrape the comments
        run: uv run src/scrape.py -d `date -I -d '-1 day'`

      - name: Analyze the comments
        run: uv run src/analyze.py -d `date -I -d '-1 day'`

      - name: Uplaod the comments
        run: uv run src/upload.py -d `date -I -d '-1 day'`
        env:
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENDPOINT_URL=${{ secrets.ENDPOINT_URL }}

      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push

